apiVersion: v1
kind: Service
metadata:
  name: {{ include "streamingapp.fullname" . }}-auth
  labels:
    {{- include "streamingapp.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth
spec:
  type: {{ .Values.auth.service.type }}
  ports:
    - port: {{ .Values.auth.service.port }}
      targetPort: {{ .Values.auth.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "streamingapp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: auth