apiVersion: v1
kind: Service
metadata:
  name: {{ include "streamingapp.fullname" . }}-mongodb
  labels:
    {{- include "streamingapp.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  type: {{ .Values.mongodb.service.type }}
  ports:
    - port: {{ .Values.mongodb.service.port }}
      targetPort: {{ .Values.mongodb.service.targetPort }}
      protocol: TCP
      name: mongodb
  selector:
    app.kubernetes.io/name: {{ include "streamingapp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: mongodb